### ISSUE TITLE
Byron MP001 Transmit

### ISSUE THREAD

**Issue by bdormael** [ssjoholm/rfxcmd#2]
I have a Byron MP001 doorbel which is support by RFXCOM but only transmit, not receive.

Via the Windows RFXCOM Manager I can ring the doorbel via the "Chimes" tab.

Is there any way I can do this by the commandline on my raspberry ?

Since receiving is not supported, I cannot listen to it to get it's ID

**Comment by ssjoholm** [comment]
Hi,

When using the RFXCOM manager, then you should see also what it will send in the yellow window, example when I did press “transmit” on chime, I received following

Chime command:07 16 00 02 00 00 01 00
0402010200
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 2
response          = ACK, data correct transmitted

If it would have chimed (I don’t have MP001) then I could have taken same command "07 16 00 02 00 00 01 00” and send it via RFXcmd.

Noted as well that under chime you need to specify the ID in the RFXmanager.

Regards,
Sebastian

**Comment by bdormael** [comment]
I have chosen the tab CHIME in the RFXMGR and then have chosen "Byron MP001" as Type, then clicked on Transmit. (Please note it is NOT ByronSX)
The bell rings on the device and I get the following output in the yellow window:

Chime command
Packettype    = Chime
subtype       = Byron MP001
Sequence nbr  = 14
ID            = 555F54
Switch 1      = Off
Switch 2      = Off
Switch 3      = Off
Switch 4      = Off
Switch 5      = Off
Switch 6      = Off
Signal level  = 0
Packettype        = Receiver/Transmitter Message
subtype           = Transmitter Response
Sequence nbr      = 14
response          = ACK, data correct transmitted

But there is no long ID like 07 16 00 02 00 00 01 00, the Byron MP001 cannot send something back, this is not supported

So the question is, how do I get then the Message to be used in 
sudo ./rfxcmd.py -v -s Message

**Comment by ssjoholm** [comment]
I had too old RFXmngr, that's why I got different result.

But the send command, when looking at your printout should be following; "07 16 01 14 55 5F 54 00"
That should represent same as you are sending. The send function in rfxcmd.py is deprecated, but should still work, try following: 

./rfxcmd.py -d <device> -s 07160101555F5400 -v

You should try to use the "rfxsaend.py" which uses the socket server in RFXcmd to send the commands.

Regards,
Sebastian

**Comment by bdormael** [comment]
Unfortunatly the command:
./rfxcmd.py -d -s 07160101555F5400 -v

doesn't do anything, it doesn't give an error either, the output is:
RFXCMD Version 0.3 (696)

Just FYI : I'm running RFXMGR on Windows (as it only exists on Windows), then I swap the RFXCOM to my Raspberry and use your RFXCMD on my Raspberry

I can't seem to find rfxsaend.py in my folder ?

**Comment by ssjoholm** [comment]
Please download last/latest GoogleCode release from here: https://github.com/ssjoholm/rfxcmd_gc/archive/0.3-beta.1.zip

**Comment by bdormael** [comment]
I think we're almost there,

I removed the -d and now I get more output, it still doesn't work though.

So I did:
sudo ./rfxcmd.py -s 07160101555F5400 -v

Output:
RFXCMD Version 0.3 (739)
Send                    = 07 16 01 01 55 5F 54 00
Date/Time               = 2015-06-09 19:00:59
Packet Length           = 07
Packettype              = Chime
Error: unrecognizable packet

If I send sudo ./rfxcmd.py -s 07160001555F5400 -v
then the output is:
RFXCMD Version 0.3 (739)
Send                    = 07 16 00 01 55 5F 54 00
Date/Time               = 2015-06-09 19:02:59
Packet Length           = 07
Packettype              = Chime
Subtype                 = Byron SX
Seqnbr                  = 01
ID                      = 555F
Sound                   = Unknown
Signal level            = 0

But ofcourse, I don't have a byronSX but an Byron MP001

So I think we just need to find the correct subtype, I tried almost every number, but no luck so far

**Comment by bdormael** [comment]
I just tried to add the -d again but now also added the device name, now it works properly :-)

The command is:
sudo ./rfxcmd.py -d  /dev/ttyUSB1 -s 07160101555F5400 -v

Thanks for all your support, it is appreciated big time.

Benny

**Comment by ssjoholm** [comment]
Good. The MP001 is missing from the identification table so that's why it said unrecognized package. I will add it now. Thank you.
